server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;

    location /portfolio {
        index index.html index.htm;
        try_files $uri $uri/ /portfolio/index.html;
    }

    # Redirect root to /portfolio
    location = / {
        return 301 /portfolio/;
    }

    # Cache static assets
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
